{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-backend
  labels:
    release: {{ quote .Values.monitoring.release | default "prometheus" }}
spec:
  selector:
    matchLabels:
      app: myapp-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-frontend
  labels:
    release: {{ quote .Values.monitoring.release | default "prometheus" }}
spec:
  selector:
    matchLabels:
      app: myapp-frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
