apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: phonebook
  namespace: argocd # or your ArgoCD namespace
spec:
  description: Phonebook dev/prod environments
  sourceRepos:
    - https://github.com/Alexbeav/devops-ci-cd-k8s-pipeline-demo.git
  destinations:
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
    - namespace: myapp-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "apps"
      kind: "Deployment"
    - group: "core"
      kind: "ConfigMap"
    - group: "core"
      kind: "Secret"
  orphanedResources:
    warn: true
