apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: phonebook
  namespace: argocd
spec:
  description: Phonebook Project
  sourceRepos:
    - 'https://github.com/Alexbeav/devops-ci-cd-k8s-pipeline-demo.git'
  destinations:
    - namespace: myapp
      server: https://kubernetes.default.svc
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
    - namespace: myapp-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phonebook-app
  namespace: argocd
spec:
  project: phonebook
  source:
    repoURL: 'https://github.com/Alexbeav/devops-ci-cd-k8s-pipeline-demo.git'
    targetRevision: main
    path: charts/myapp
    helm:
      valueFiles:
        - values.yaml
  destinations:
    - namespace: myapp
      server: https://kubernetes.default.svc
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
    - namespace: myapp-prod
      server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
