nameOverride: myapp-dev
# IMPORTANT: When deploying to dev, use Helm release name 'myapp-dev' (or Argo CD app name 'myapp-dev')
# This ensures all resources (including PostgreSQL service) are named correctly for the dev environment.
postgresql:
ingress:
  host: myapp-dev.example.com
monitoring:
  enabled: false
  release: prometheus
backend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/backend
  tag: "d90f4ad"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
frontend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/frontend
  tag: "1d9cd60"
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
# Database (PostgreSQL) configuration
postgresql:
  enabled: true
  auth:
    username: myappuser
    password: myapppassword
    database: myappdb
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ''
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - exec pg_isready -U myappuser -d myappdb -h 127.0.0.1
      initialDelaySeconds: 70
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    readinessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - exec pg_isready -U myappuser -d myappdb -h 127.0.0.1
      initialDelaySeconds: 40
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5

