monitoring:
  enabled: false
  release: prometheus
backend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/backend:latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
frontend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/frontend:latest
  replicaCount: 1
  service:
monitoring:
  enabled: false
backend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/backend
  tag: e55c832
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
frontend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/frontend
  tag: e55c832
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
# Database (PostgreSQL) configuration
postgresql:
  enabled: true
  auth:
    username: myappuser
    password: myapppassword
    database: myappdb
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ''

# Environment toggles (dev/prod)
environment: dev # or prod
replicaCount:
  frontend: 1
  backend: 1
