nameOverride: myapp-prod
environment: prod
ingress:
  host: myapp.example.com
  useIngressRoute: true # Set to true to use Traefik IngressRoute instead of standard Ingress
  tls:
    enabled: true
    certResolver: letsencrypt
monitoring:
  enabled: true
  release: prometheus
backend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/backend
  tag: "1d59818"
  replicaCount: 3
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
frontend:
  image: ghcr.io/alexbeav/devops-ci-cd-k8s-pipeline-demo/frontend
  tag: "193fd85"
  replicaCount: 3
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
postgresql:
  enabled: true
  fullnameOverride: myapp-postgresql
  auth:
    username: myappuser
    password: myapppassword
    database: myappdb
  primary:
    persistence:
      enabled: true
      size: 32Gi
      storageClass: ''
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - exec pg_isready -U myappuser -d myappdb -h 127.0.0.1
      initialDelaySeconds: 70
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    readinessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - exec pg_isready -U myappuser -d myappdb -h 127.0.0.1
      initialDelaySeconds: 40
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
