backend:
  image: ghcr.io/alexbeav/backend:latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
frontend:
  image: ghcr.io/alexbeav/frontend:latest
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
